### PR TITLE
Check this Commits a small Contribution What I Can Do For Your Hard Work

### PR DESCRIPTION
**Pull request by sppidy**

### CODE REVIEW

**Comment by rojserbest** [comment]
@sppidy I closed this, I hated the punctuation.

**Comment by rojserbest** [comment]
@rojserbest !oops

**Comment by sppidy** [comment]
> @sppidy I closed this, I hated the punctuation.

A Small Thing To Clear That . This is Not CallsMusic Repo to Close PRs For Your Self Let @xencodes Tell

**Comment by rojserbest** [comment]
Lol that message wasn't to be sent. Anyway, @xencodes agrees.

**Pull request closed without merging**
