### PR TITLE
Edited Loprsem Texts in Setup Pages

### PR DESCRIPTION
**Pull request by sppidy**
Check this Commits a small Contribution What I Can Do For Your Hard Work

### CODE REVIEW

**Review by xencodes — APPROVED** [review]
this looks like a good message text

**Review by xencodes — CHANGES_REQUESTED** [review]
"Get this value from https://my.telegram.org" shouldn't be told inside a placeholder.

We'll need an additional header text for this.

**Comment by sppidy** [comment]
> `"Get this value from https://my.telegram.org"` shouldn't be told inside a placeholder.
> 
> We'll need an additional header text for this.

ok

**Comment by sppidy** [comment]
@xencodes Please Review Again

**Comment by xencodes** [comment]
> @xencodes Please Review Again

Can you post a **screenshot** what does it look like? I'm at store right now, I cannot check.

**Comment by sppidy** [comment]
> > @xencodes Please Review Again
> 
> Can you post a **screenshot** what does it look like? I'm at store right now, I cannot check.

Yep Ok

**Comment by sppidy** [comment]
> > @xencodes Please Review Again
> 
> Can you post a **screenshot** what does it look like? I'm at store right now, I cannot check.

Screenshot 2021-07-12 8 29 46 AM

**Comment by xencodes** [comment]
@sppidy can you move "Get this value...." from both input labels and put them after the heading text, after "...information.". Because, both labels have the same text, would be better if they're placed at one position.

**Comment by sppidy** [comment]
> @sppidy can you move "Get this value...." from both input labels and put them after the heading text, after "...information.". Because, both labels have the same text, would be better if they're placed at one position.

Yeah ok

**Comment by sppidy** [comment]
\

> @sppidy can you move "Get this value...." from both input labels and put them after the heading text, after "...information.". Because, both labels have the same text, would be better if they're placed at one position.

I have Did Something More better than Header

**Comment by sppidy** [comment]
> > @xencodes Please Review Again
> 
> Can you post a **screenshot** what does it look like? I'm at store right now, I cannot check.

image

**Comment by xencodes** [comment]
You still have an improper heading. You've put "to learn more about it...", what does it imply?

**Comment by sppidy** [comment]
> You still have an improper heading. You've put "to learn more about it...", what does it imply?

It was Given by Quilbot

**Comment by sppidy** [comment]
> You still have an improper heading. You've put "to learn more about it...", what does it imply?

image

**Comment by xencodes** [comment]
This looks cool. Thanks for you time @sppidy. I'm going to merge this.

**Comment by sppidy** [comment]
> This looks cool. Thanks for you time @sppidy. I'm going to merge this.

Thanks

**Pull request merged**
